dolittle/vanir

.vscode/settings.json, Source/typescript/cli/PlopHelper.ts, Source/typescript/cli/package.json, Source/typescript/create-dolittle-app/creation.ts, Source/typescript/create-dolittle-microservice/creation.ts
This works better in a WebPacked scenario
=> Changing to using the required plopfile rather than the file

Source/typescript/backend/web/Context.ts
Fixes so that the correct context is returned.
- Fixes so that the correct context is returned - not the default one.
=> Fixing the return of the actual context

Samples/Source/Typescript/Backend/DoStuff.ts, Samples/Source/Typescript/Backend/NoQueries.ts, Samples/Source/Typescript/Backend/Nothing.ts, Samples/Source/Typescript/Backend/index.ts, Source/typescript/backend/data/GraphQLSchema.ts
Making sure we have the right context both for regular Express middlewares and GraphQL.
- Fixes so that the context is correct in all call paths
=> remove-unused-code

Source/typescript/create-dolittle-microservice/templates/backend/Source/{{ pascalCase name }}/k8s/Development/configmap.yml
update the configmap for dev to reflect new cluster config structure
- update the configmap for dev to reflect new cluster config structure
=> update k8s dev template to new structure

Source/typescript/create-dolittle-microservice/templates/backend/Source/{{ pascalCase name }}/k8s/Production/configmap.yml
update prod configmap template to reflect new structure
- update prod configmap template to reflect new structure
=> update prod configmap template to new structure

Source/typescript/create-dolittle-microservice/templates/backend/Source/{{ pascalCase name }}/k8s/Development/configmap.yml, Source/typescript/create-dolittle-microservice/templates/backend/Source/{{ pascalCase name }}/k8s/Production/configmap.yml
Fixing the scaffolding.
- Fixes [#135](https://github.com/dolittle-entropy/vanir/issues/135) - casing issue in templates.
=> Fixes casing on lowercase -> lowerCase

.github/workflows/publish.yml
Shaping up the C# setup for resources, graphql and all.
- [C#] Support for taking dependency to IMongoDatabase and it resolve to correct tenant based on resources.json config file
- [C#] GraphQL routes adhering to the vanir.json file setup
- [C#] ExecutionContext setup properly based on the Tenant-ID HTTP header
- [C#] Microservice.json configuration support added - ExecutionContext leverages this
=> Fixing typo for option for package version

.github/workflows/publish.yml
Shaping up the C# setup for resources, graphql and all.
- [C#] Support for taking dependency to IMongoDatabase and it resolve to correct tenant based on resources.json config file
- [C#] GraphQL routes adhering to the vanir.json file setup
- [C#] ExecutionContext setup properly based on the Tenant-ID HTTP header
- [C#] Microservice.json configuration support added - ExecutionContext leverages this
=> Adding Nuget output path

Samples/Source/Aspnetcore/Backend/Program.cs, Samples/Source/Aspnetcore/Backend/Things.cs, Source/DotNET/Backend/Backend.csproj, Source/DotNET/Backend/Config/Configuration.cs, Source/DotNET/Backend/Container.cs, Source/DotNET/Backend/GraphQL/GraphController.cs, Source/DotNET/Backend/GraphQL/GraphControllers.cs, Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs, Source/DotNET/Backend/GraphQL/ICanHaveName.cs, Source/DotNET/Backend/GraphQL/IGraphControllers.cs, Source/DotNET/Backend/GraphQL/Mutation.cs, Source/DotNET/Backend/GraphQL/MutationAttribute.cs, Source/DotNET/Backend/GraphQL/MutationType.cs, Source/DotNET/Backend/GraphQL/ObjectTypeExtensions.cs, Source/DotNET/Backend/GraphQL/Query.cs, Source/DotNET/Backend/GraphQL/QueryAttribute.cs, Source/DotNET/Backend/GraphQL/QueryType.cs, Source/DotNET/Backend/IContainer.cs, Source/DotNET/Backend/Resources/ResourcesServiceCollectionExtensions.cs, Source/DotNET/Backend/RuntimeEnvironment.cs, Source/DotNET/Backend/VanirAppBuilderExtensions.cs, Source/DotNET/Backend/VanirServiceCollectionExtensions.cs
Making it simpler to work with Hot Chocolate type of GraphQL - heavily influenced by GraphQL AspNetCore.
- GraphController, QueryAttribute nad MutationAttribute - as found in GraphQL AspNetCore
=> hotchocolate-graphql

Samples/Source/Aspnetcore/Backend/Backend.csproj, Samples/Source/Aspnetcore/Backend/CreditCardNumberType.cs, Samples/Source/Aspnetcore/Backend/Startup.cs, Source/DotNET/Backend/Backend.csproj, Source/DotNET/Backend/BackendArguments.cs, Source/DotNET/Backend/Collections/CollectionExtensions.cs, Source/DotNET/Backend/GraphQL/GraphControllers.cs, Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs, Source/DotNET/Backend/Reflection/ContractToImplementorsMap.cs, Source/DotNET/Backend/Reflection/IContractToImplementorsMap.cs, Source/DotNET/Backend/Reflection/ITypes.cs, Source/DotNET/Backend/Reflection/MultipleTypesFound.cs, Source/DotNET/Backend/Reflection/TypeExtensions.cs, Source/DotNET/Backend/Reflection/Types.cs, Source/DotNET/Backend/Reflection/UnableToResolveTypeByName.cs, Source/DotNET/Backend/VanirServiceCollectionExtensions.cs
- Convenient Collection Extensions
- Simple type discovery for project referenced assemblies
- Automatic hook up of any `ScalarType` / `ScalarType<>` implementations
- Ability to configure Hot Chocolate GraphQL properties manually
=> graphql-added-features

Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs, Source/DotNET/Backend/GraphQL/NamingConventions.cs
- Enum naming convention adds a suffix of enum to type name
=> Default type name for enums are now suffixed with enum

Source/DotNET/Backend/GraphQL/Validation/Validators.cs
- Avoid getting duplicate keys for the population of validation types by type
=> Fixes a problem with duplicate keys when populating validation types

Samples/Source/Aspnetcore/Backend/Backend.csproj, Samples/Source/Aspnetcore/Backend/Things.cs, Source/DotNET/Backend/Dolittle/DolittleServiceCollectionExtensions.cs, versions.props
- Aggregate root support through dependency injection of IAggregateOf<>
- Updated dependencies to the latest version of the Dolittle SDK (8.3.2)
=> Adding aggregate root support

Source/DotNET/Backend/BackendArguments.cs, Source/DotNET/Backend/Resources/ResourcesServiceCollectionExtensions.cs, Source/DotNET/Backend/VanirServiceCollectionExtensions.cs
- [C#] Added a callback to the BackendArguments to be able to configure the Mongo DB settings before they're frozen for the client instance
=> Adding a callback for configuring Mongo settings

Source/Tooling/CLI/CLI.csproj
- Fixing metadata for CLI package so that it hopefully shows up in NuGet as a tool
=> Adding package metadata

Source/typescript/backend/package.json, Source/typescript/cli/package.json, Source/typescript/common/package.json, Source/typescript/create-dolittle-app/package.json, Source/typescript/create-dolittle-microservice/package.json, Source/typescript/dependency-inversion/package.json, Source/typescript/features/package.json, Source/web/package.json, Source/webpack/package.json
=> Fixing version number

.github/workflows/publish.yml, Source/Tooling/CLI/CLI.csproj
- Correct package information for the CLI to be able to PackAsTool
=> fix-toolpackage

Source/Tooling/Visual/package.json
=> Disable prebuild task

Documentation/README.md, Documentation/cli.md, Documentation/feature-toggling/cli/index.md, Samples/Source/Aspnetcore/Backend/data/features.json, Source/Tooling/Visual/package.json, Source/Tooling/vscode/package.json
=> Adding CLI docs

Source/typescript/backend/package.json, Source/typescript/cli/package.json, Source/typescript/common/package.json, Source/typescript/create-dolittle-app/package.json, Source/typescript/create-dolittle-microservice/package.json, Source/typescript/dependency-inversion/package.json, Source/typescript/features/package.json, Source/web/package.json, Source/webpack/package.json
=> Aligning versions

Source/DotNET/Backend/Dolittle/DolittleServiceCollectionExtensions.cs
- [C#] Hooked up the last piece of the puzzle for `event-horizons.json` to be parsed and set up. Forgotten to that.
=> Hooking up event horizons

.editorconfig, CodeAnalysis.ruleset, Source/DotNET/Backend/Backend.csproj, Source/DotNET/Backend/Dolittle/DolittleServiceCollectionExtensions.cs, Source/DotNET/Backend/Dolittle/EventMutationFor.cs, Source/DotNET/Backend/Dolittle/EventStreamSubscription.cs, Source/DotNET/Backend/Features/FeaturesSubscriptionsResolver.cs, Source/DotNET/Backend/GraphQL/GraphQLAppBuilderExtensions.cs, Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs, Source/DotNET/Backend/Validation/Validators.cs, default.props
- [C#] Adding `.ConfigureAwait(false)` to all async calls - adhering to the recommendations for libraries based on the following article; https://devblogs.microsoft.com/dotnet/configureawait-faq/
=> configureawait

Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs
- Improved the approach to how we invoke actual validators
- Added exception handling to catch potential errors and report them more accurately if invocation fails for validators
=> Changing how we invoke validation + catching errors and reporting

Source/typescript/backend/dolittle/index.ts
- Logging for event horizon setup from config - make it possible to trace whats going on.
=> Adding logging for event horizon setup

.github/workflows/build.yml, Source/webpack/package.json
Worfklow update to run node and dotnet build remote + webpack-cli package update
- Fixes webpack build
- Workflows not working
=> Worklow + Webpack-cli package update
