dolittle/vanir

Source/typescript/cli/PathHelper.ts
Source/typescript/cli/PlopHelper.ts
Source/typescript/cli/index.ts
Source/typescript/create-dolittle-app/plopfile.ts
Source/typescript/create-dolittle-microservice/plopfile.ts

There is an issue in Globby which is being used in Plop that
causes problems with normalized paths that end up using
Windows style path separator. A workaround is to change it
to Unix style for the patterns.

Fixing glob patterns to work correctly for underlying Globby

---

Source/web/Bindings.ts

Fixing a problem with the path for GraphQL client - needs a trailing /
- Added trailing slash for GraphQL paths for the client bindings

Adding trailing / for graphql path

---

Samples/Source/Aspnetcore/Web/package.json
Samples/Source/Portal/Web/package.json
Samples/Source/Typescript/Web/package.json
Source/web/package.json
Source/webpack/package.json

We've had issues with WebPack when using the dev-server and also all of a sudden broken builds due to the html-webpack-plugin not loading the ejs template file and rendering it.
- Upgraded to latest WebPack
- Upgraded to latest html-webpack-plugin
- Removing --watch option
- Updating templates to use webpack instead of webpack-cli directly

upgrade-webpack

---

Source/typescript/create-dolittle-microservice/templates/backend/Source/{{ pascalCase name }}/k8s/Production/configmap.yml

This PR fixes the hardcoded "Dolittle" tenant in the k8s production configuration to be configurable per template
- Fix the hardcoded "Dolittle" tenant in the k8s production configuration to be configurable per template

Fix the hardcoded "Dolittle" tenant in the k8s production configuration to be configurable per template

---

Documentation/microservice.md
Source/typescript/backend/web/Context.ts

Typo when getting HTTP header for Tenant
- Fixing usage of correct HTTP header for tenant; Tenant-ID not Tenant-Id

Fixing capitalization for Tenant-ID not Tenant-Id

---

Source/typescript/backend/Host.ts
Source/typescript/backend/HostContext.ts
Source/typescript/backend/data/GraphQLSchema.ts
Source/typescript/backend/mongodb/MongoDbContext.ts
Source/typescript/backend/web/Context.ts
Source/typescript/backend/web/Express.ts

Making sure we have the right context both for regular Express middlewares and GraphQL.
- Fixes so that the context is correct in all call paths

Wrap Host runner in a CLS namespace run and use it for context

---

Source/typescript/create-dolittle-microservice/templates/portal/Source/{{ pascalCase name }}/Web/package.json.hbs

- the start:dev script in portal template does not work with cli, update to use webpack directly
- the start:dev script in portal template does not work with cli, update to use webpack directly

make start dev work in portal template

---

Source/typescript/create-dolittle-microservice/templates/web/Source/{{ pascalCase name }}/Web/package.json.hbs

the start:dev script in web template does not work with cli, update to use webpack directly
- the start:dev script in web template does not work with cli, update to use webpack directly

make start:dev work

---

Documentation/frontend/anatomy-of-a-frontend.md
Source/typescript/create-dolittle-microservice/templates/portal/Source/{{ pascalCase name }}/Web/package.json.hbs
Source/typescript/create-dolittle-microservice/templates/web/Source/{{ pascalCase name }}/Web/package.json.hbs

Makes scaffolding of new projects correct.
- Fixes so we don't use webpack-cli but webpack directly for yarn:dev scripts in package.json

Fixes webpack:dev scripts to use webpack and not webpack-cli

---

Source/typescript/backend/index.ts

Exporting sub modules.
- To avoid consumers of packages having to import `dist` relative paths within the package, we now export the sub-modules as part of the top-level package (e.g. data will be @dolittle/vanir-backend/data instead of @dolittle/vanir-backend/dist/data)

Exporting all sub modules to avoid dist imports

---

Source/typescript/backend/index.ts

Making GuidScalar more available
- Exporting GuidScalar from root module @dolittle/vanir-backend

Exporting GuidScalar at top

---

.vscode/settings.json
Source/typescript/backend/mongodb/CollectionNamePluralizer.ts
Source/typescript/backend/mongodb/MongoDatabase.ts
Source/typescript/backend/mongodb/index.ts

This fixes an undesired breaking change from version 8 to 9. Collection names would by default be the type name- but we expect the same default behavior as with Mongoose, which is making it lowercase and pluralized. This particular code is now brought in from Mongoose to make sure we have the same behavior and is as expected.
- Collection names are now correct; lowercase + pluralized

Default collection name compatibility with Mongoose

---

Source/DotNET/Backend/Config/Configuration.cs

- When paths are rooted as described in `vanir.json` - the GraphQL paths will now be single / at the beginning.

Avoid getting double / for rooted paths

---

Samples/Source/Aspnetcore/Backend/Owner.cs
Samples/Source/Aspnetcore/Backend/Things.cs
Source/DotNET/Backend/Concepts/ConceptExtensions.cs
Source/DotNET/Backend/Concepts/ConceptFactory.cs
Source/DotNET/Backend/Concepts/ConceptMap.cs
Source/DotNET/Backend/Concepts/TypeIsNotAConcept.cs
Source/DotNET/Backend/GraphQL/Concepts/ConceptAsGraphQLBuilderExtensions.cs
Source/DotNET/Backend/GraphQL/Concepts/ConceptAsTypeProvider.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/GraphQL/ObjectTypeExtensions.cs
Source/DotNET/Backend/Reflection/ITypeInfo.cs
Source/DotNET/Backend/Reflection/TypeConstructorExtensions.cs
Source/DotNET/Backend/Reflection/TypeExtensions.cs
Source/DotNET/Backend/Reflection/TypeInfo.cs

- ConceptAs extensions to make it easier to work with ConceptAs
- Reflection extensions to make it easier to work with type reflection
- Automatic hookup of Type conversion for GraphQL for ConceptAs and base type mapping. This enables use of concepts in any GraphQL construct (ObjectType) and it will map to the underlying system type it is a concept as of.

Adding full support for any Concepts - automatic conversion to base type

---

Samples/Source/Aspnetcore/Backend/Things.cs
Source/DotNET/Backend/Backend.csproj
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/GraphQL/Validation/IValidators.cs
Source/DotNET/Backend/GraphQL/Validation/ValidationExtensions.cs
Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs
Source/DotNET/Backend/GraphQL/Validation/Validators.cs
Source/DotNET/Backend/Reflection/ContractToImplementorsMap.cs
Source/DotNET/Backend/Reflection/ExpressionExtensions.cs
Source/DotNET/Backend/Reflection/MethodCalls.cs
Source/DotNET/Backend/Strings/StringExtensions.cs
Source/DotNET/Backend/VanirServiceCollectionExtensions.cs

- `GraphRoot` attribute that will enable you to set the root object - can be nested, delimited by /
- `Query` attribute now supports path relative to `GraphRoot` or root if not `GraphRoot` is used - can be nested, delimited by /
- `Mutation` attribute now supports path relative to `GraphRoot` or root if not `GraphRoot` is used - can be nested, delimited by /
- Support for FluentValidations AbstractValidator - automatically hooked up on any input arguments
- AbstractValidator<> can be for any type - any input type with a property of a type with a validator will be evaluated as well

graphql-validation

---

Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs

- Skip properties in validation recursion when property type is of same as parent to avoid stack overflow exception

Skipping properties of same type as parent for validation

---

Samples/Source/Aspnetcore/Backend/Things.cs
Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs

- Removes ".Value" for concepts being set using .SetValidator typically
- Does not add errors that are already there - avoids duplicate error messages for same proprty if one has added multiple instances of same validator

Making sure we don't get duplicate errors and correct for concepts

---

Source/DotNET/Backend/Services.cs
Source/DotNET/Backend/VanirServiceCollectionExtensions.cs

- `AddVanir()` now returns a `Services` object that holds for now the `ITypes` for type discovery but can then be expanded on in the future.

Returning service(s) setup by AddVanir()

---

Source/DotNET/Backend/Dolittle/DolittleEventMutationsExtensions.cs
Source/DotNET/Backend/Dolittle/EventMutationFor.cs
Source/DotNET/Backend/GraphQL/GraphQLBuilderExtensions.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs

- Exposing all event types based on types discovered into the GraphQL schema under mutation. Names are linked to the typename. This allowes for `mutation { events { ...nameOfEventType } }`

Extending GraphQL schame with events and all the event types discovered

---

Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs

- Event mutations should only be exposed when running in development

Only add event mutations when in development mode

---

Samples/Source/Aspnetcore/Backend/GroceryStore/Bakery/BakeryController.cs
Source/DotNET/Backend/GraphQL/GraphQLBuilderExtensions.cs

- Enabling queries and mutations to live on the same route by postfixing the types used within Query and Mutation types and their children. Postifxes are "Queries" and "Mutations" for the types.

Postfixing types resolved from routes with its type (Queries / Mutations)

---

.vscode/launch.json
Samples/.dolittle/Typescript/resources.json
Samples/.dolittle/docker-compose.yml
Samples/.dolittle/nginx.conf
Source/typescript/backend/BackendArguments.ts
Source/typescript/backend/Host.ts
Source/typescript/backend/aggregates/Aggregate.ts
Source/typescript/backend/aggregates/BrokenRule.ts
Source/typescript/backend/aggregates/IAggregate.ts
Source/typescript/backend/aggregates/index.ts
Source/typescript/backend/data/BrokenRuleErrorInterceptor.ts
Source/typescript/backend/data/GraphQLSchema.ts
Source/typescript/backend/dolittle/IEventStore.ts
Source/typescript/backend/dolittle/index.ts
Source/typescript/backend/index.ts
Source/typescript/backend/package.json

- eventTypes and eventHandlerTypes can now be configured during start of host
- BrokenRule, typically used in aggregates to convey when something is not allowed - a broken rule
- Aggregate support for IoC purposes
- Upgraded to version 14.3.0 of the TypeScript SDK
- Upgraded to version 2.0.0 of the Dolittle declarative projections
- Upgraded samples to use vrsion 5.5.0 of the Dolittle Runtime

aggregate-roots

---

Source/typescript/backend/package.json

- @dolittle/projections upgraded to v2.1.0 for supporting Guid conversion to and from Mongo

Upgrading to @dolittle/projections 2.1.0

---

Source/react/package.json
Source/web/package.json

- Apollo + GraphQL dependencies moved from React to Web - which is more correct. If you don't use React, you'll then get the dependencies we really rely on.

Move Apollo + GraphQL dependencies to Web

---

Samples/Source/Aspnetcore/Backend/Things.cs
Source/DotNET/Backend/GraphQL/Validation/IValidators.cs
Source/DotNET/Backend/GraphQL/Validation/ValidationMiddleware.cs
Source/DotNET/Backend/GraphQL/Validation/Validators.cs

- [C#] During GraphQL calls, all validators for a type using FluentValidation is now included automatically. Not just the first it discovers.

Fixed so that it includes all validators for a type - not just the first it discovers

---

Samples/Source/Aspnetcore/Backend/Things.cs

- [C#] Added a default public filter that will forward all events applied/committed as public - this behavior can be overridden by setting `PublishAllPublicEvents` in the `BackendArguments` used in `AddVanir()` method to false. You can then use the Dolittle configuration callback to configure your filter instead: https://dolittle.io/docs/tutorials/event-horizon/
- [C#] All types adorned with the [Projection] attribute are automatically registered as projections. Read more here: https://dolittle.io/docs/tutorials/projections/
- [C#] Upgraded to version 8.4.0 of the SDK

trigger-publish

---

Samples/Source/Aspnetcore/Backend/Things.cs
Source/DotNET/Backend/Dolittle/DolittleContainer.cs
Source/DotNET/Backend/Dolittle/DolittleServiceCollectionExtensions.cs
Source/DotNET/Backend/Execution/ExecutionContextAppBuilderExtensions.cs
Source/DotNET/Backend/Execution/ExecutionContextManager.cs
Source/DotNET/Backend/Execution/ExecutionContextServiceCollectionExtensions.cs
Source/DotNET/Backend/Execution/IExecutionContextManager.cs
Source/DotNET/Backend/Resources/ResourcesServiceCollectionExtensions.cs
Source/DotNET/Backend/VanirAppBuilderExtensions.cs
Source/DotNET/Backend/VanirServiceCollectionExtensions.cs

- [C#] `IExecutionContextManager` interface - making it possible not lock one into the implementation. This enables more predictability for automated tests, which could potentially have side-effects with its async local implementation for holding current.

execution-context

---

Source/DotNET/Backend/BackendArguments.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/VanirServiceCollectionExtensions.cs
Source/typescript/features/featureDecorator.ts
Source/typescript/features/for_Dummy/when_nothing.ts

- [C#] `BackendArguments` now have a property called `ExposeEventsInGraphQLSchema` that enables you to disable the exposure of events in the GraphQL schema in development mode. This setting is set to true as default.
- [C#] Crash when not passing in a `BackendArguments` instance to `.AddVanir()` (#223). It is now possible to not pass anything in.

small-bug-fixes

---

Samples/Source/Aspnetcore/Backend/Owner.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/GraphQL/ReadOnlyPropertyInterceptor.cs

- [C#] Added Hot Chocolate type interceptor for adding read only properties on object types and making them readable during execution (#226)

Adding support for read-only properties in Schema + execution

---

Source/DotNET/Backend/GraphQL/Concepts/ConceptAsTypeProvider.cs

- [C#] Removing new() constraint on ConceptAs type provider - this was an error, it shouldn't have this constraint as we support creating instances of Concept types without default constructors.

Remove new() constraint on concepts - they can have non-default constructors

---

Documentation/backend/DotNET/index.md
Documentation/backend/DotNET/startup.md
Samples/Source/Aspnetcore/Backend/Startup.cs
Source/DotNET/Backend/Dolittle/DolittleAppBuilderExtensions.cs
Source/DotNET/Backend/Dolittle/DolittleServiceCollectionExtensions.cs
Source/DotNET/Backend/GraphQL/GraphQLAppBuilderExtensions.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/Services.cs
Source/DotNET/Backend/VanirAppBuilderExtensions.cs
Source/DotNET/Backend/VanirServiceCollectionExtensions.cs

- Documentation added for how `Startup` works
- Includes exception details during development on GraphQL operations
- `.AddVanir()` and `.UseVanir()` are less opionated. If one wants the same level of opinions, use `.AddVanirWithCommon()` and `.UseVanirWithCommon()`.

Add flexibility for Startup configuration

---

Samples/Source/Aspnetcore/Backend/Owner.cs
Source/DotNET/Backend/GraphQL/EnumToIntConverter.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs

- [C#] For consistency with the Node version, we want enums to be integers by default - by default now it adds a type conversion for this.

enum-as-int

---

Source/DotNET/Backend/GraphQL/EnumExtensions.cs
Source/DotNET/Backend/GraphQL/GraphQLBuilderExtensions.cs
Source/DotNET/Backend/GraphQL/GraphQLServiceCollectionExtensions.cs
Source/DotNET/Backend/GraphQL/SchemaRoute.cs

- [C#] Support type conversion to integer for enum types on the actual ObjectTypes and InputObjectTypes used by queries and mutations. This enables enums from 3rd party assemblies.

Recursively getting the types from the actual aggregated queries and mutations for enums

---

Source/DotNET/Backend/GraphQL/EnumExtensions.cs

- [C#] Fixes a stack overflow when registering enums as ints if any type is recursively referencing itself anywhere in the tree.

Making sure we don't scan same type recursively

---

Source/DotNET/Backend/Dolittle/DolittleAppBuilderExtensions.cs

- [C#] Fixing so that the Client instance is set before we start the client - this will then make IoC resolver callbacks relying directly or indirectly work.

Reorder initialization to make Client object available for IOC

---

Source/typescript/backend/web/Express.ts

- [TS/JS] Express callback was too late. Moved it up the stack - before the Apollo GraphQL middlewares are applied. This enables adding middlewares much earlier.

Moving express callback earlier

---

Source/web/Bindings.ts

- [Web] Fixing so that when origin of document is HTTPS we use WSS for WebSocketLink for GraphQL and WS if HTTP.

Making WebSocketLink use WSS if origin is TLS

---

Source/typescript/backend/package.json

- [Node] Upgrading to version 16.0.0 of the Dolittle SDK and 2.1.2 of the Dolittle Projections.

Upgrading SDK + Projections

---

versions.props

- [.NET] Upgrade to version 9.0.0 of the Dolittle SDK

Update .NET SDK version

---

Source/typescript/backend/package.json
versions.props

- Upgraded to version 17.0.1 of the Dolittle SDK
- Upgraded to version 2.1.3 of Dolittle Entropy Projections (for compatibility with SDK)

Upgrading to version 2.1.3 of Projections + 17.0.1 of SDK

---

Source/typescript/backend/graphql/GuidExtensions.ts
Source/typescript/backend/mongodb/GuidCustomType.ts

Removes the `toGuid()` extension method on `mongodb.Binary`. It was failing builds and we couldn't fix it. It has been replaced with a normal function `binaryToGuid(...)`.
- [TS] The `.toGuid()` extension methods on `mongodb.Binary`.

Remove the Binary.toGuid() to make TS builds work

---

.github/workflows/publish.yml

Closes #267. Thanks @rune-wikstad! I couldn't figure out how to build a remote PR. 
Also moved the creation of a GitHub release and updating the CHANGELOG.md file to after the packages have been published in the `.github/publish.yml` action.
- [C#] A bug in the `ValidationMiddleware` setting `errors` to the literal string `"errors"` instead of the list of errors.

Fix validation middleware bug
